syntax = "proto3";

package bedrock.experience.v1;

option go_package = "github.com/JWartofsky3/BedrockExperienceMaker/api/gen/go/bedrock/experience/v1;experiencev1";

import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

message Addon {
  option (google.api.resource) = {
    type: "bedrockexperiencemaker.local/Addon"
    pattern: "addons/{addon}"
  };

  string name = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
  string display_name = 2 [(google.api.field_behavior) = REQUIRED];
  string creator_name = 3;
  string description = 4;
  string icon_path = 5;
  string curseforge_url = 6;
  string mcpedl_url = 7;
  string current_version = 8;
  string minecraft_version_note = 9;
  google.protobuf.Struct manifest_data = 10;
  google.protobuf.Timestamp create_time = 11 [(google.api.field_behavior) = OUTPUT_ONLY];
  google.protobuf.Timestamp update_time = 12 [(google.api.field_behavior) = OUTPUT_ONLY];
  repeated AddonDependency dependencies = 13 [(google.api.field_behavior) = OUTPUT_ONLY];
}

message AddonDependency {
  string name = 1 [(google.api.resource_reference) = {type: "bedrockexperiencemaker.local/Addon"}];
  string display_name = 2 [(google.api.field_behavior) = OUTPUT_ONLY];
}

message ExperiencePack {
  option (google.api.resource) = {
    type: "bedrockexperiencemaker.local/ExperiencePack"
    pattern: "packs/{pack}"
  };

  string name = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
  string display_name = 2 [(google.api.field_behavior) = REQUIRED];
  string creator_name = 3 [(google.api.field_behavior) = OUTPUT_ONLY];
  string description = 4;
  string setup_notes = 5;
  repeated PackAddon addons = 6 [(google.api.field_behavior) = OUTPUT_ONLY];
  google.protobuf.Timestamp create_time = 7 [(google.api.field_behavior) = OUTPUT_ONLY];
  google.protobuf.Timestamp update_time = 8 [(google.api.field_behavior) = OUTPUT_ONLY];
}

message User {
  option (google.api.resource) = {
    type: "bedrockexperiencemaker.local/User"
    pattern: "users/{user}"
  };

  string name = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
  string username = 2 [(google.api.field_behavior) = OUTPUT_ONLY];
}

message PackAddon {
  Addon addon = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
  int32 install_order = 2 [(google.api.field_behavior) = OUTPUT_ONLY];
  string note = 3;
}
